// app/layouts/RootLayout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
// import "../styles/globals.css"; // Adjust the path if necessary
import './globals.css'
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";

// const geistSans = localFont({
//   src: "../fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "../fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProvider defaultTheme="system" enableSystem={true} attribute="class">
            <main>{children}</main>
            <Toaster></Toaster>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
